name: Python Linting

on:
  push:
  pull_request:

jobs:
  build:
    name: Python Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.14'

    - name: Install Python Deps
      run: source ci/python.sh && qa_prepare_all

    - name: Lint MicroPython Examples
      shell: bash
      run: source ci/python.sh && qa_examples_check

    - name: Lint MicroPython Modules
      shell: bash
      run: source ci/python.sh && qa_modules_check

    - name: Lint Python Tools
      shell: bash
      run: source ci/python.sh && qa_tools_check